# Generated by Django 2.2 on 2022-01-13 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('shop', '0002_products'),
        ('cart', '0002_auto_20220113_1121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='product',
            new_name='prodt',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='quantity',
            new_name='quan',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
    ]
