# Generated by Django 2.2 on 2022-01-13 11:02

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('cart', '0003_auto_20220113_1248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='cartlist',
        ),
    ]
